version: '3'

services:
  db:
    restart: always
    container_name: postgree
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_PASSWORD=dev
      - POSTGRES_USER=dev
      - POSTGRES_DB=trie
    ports:
      - "5432:5432"
    volumes:
      - ./src/utils/database/init.sql:/docker-entrypoint-initdb.d/init.sql
